before_script:
  - echo "before_script"
stages:
  - build
  - init
  - deploy
初始化任务:
  stage: init
  tags:
    - devops
  script:
    - echo "初始化任务"

buildJob:
  stage: build
  tags:
    - devops
  script:
    - echco "打包任务"
  allow-failure: true

DeployJob:
  stage: deploy
  tags:
    - devops
  script:
    - echo "DeployJob"