stages:
  - build
  - init
  - deploy
初始化任务:
  stage: init
  tags:
    - devops
  script:
    - echo "初始化任务"

buildJob:
  stage: build
  tags:
    - devops
  script:
    - echo "打包任务"

DeployJob:
  stage: deploy
  tags:
    - devops
  script:
    - echo "DeployJob"