# Generated by Django 2.2 on 2020-07-01 10:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='文章分类')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名', max_length=40, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文内容')),
                ('create', models.DateField(default=datetime.datetime(2020, 7, 1, 10, 49, 37, 689302, tzinfo=utc), verbose_name='创建日期')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('ategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleCategory', verbose_name='文章分类')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='文章作者')),
            ],
        ),
    ]
