# Generated by Django 2.2 on 2020-07-02 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterModelOptions(
            name='articlepost',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='create',
            field=models.DateField(default=datetime.datetime(2020, 7, 2, 3, 0, 44, 482256, tzinfo=utc), verbose_name='创建日期'),
        ),
    ]
