# Generated by Django 2.2 on 2020-07-02 03:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200702_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='create',
            field=models.DateField(default=datetime.datetime(2020, 7, 2, 3, 4, 49, 169817, tzinfo=utc), verbose_name='创建日期'),
        ),
        migrations.AlterModelTable(
            name='articlecategory',
            table='article_category',
        ),
        migrations.AlterModelTable(
            name='articlepost',
            table='article_post',
        ),
    ]
