# Generated by Django 2.2 on 2020-07-02 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200702_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='create',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
    ]
